services:
  gateway:
    image: re.giomartins.dev/gateway:latest
    ports:
      - "3002:3000"
    environment:
      FAAS_GATEWAY_URL: https://of.giomartins.dev
      CF_ACCESS_CLIENT_ID: ${CF_ACCESS_CLIENT_ID}
      CF_ACCESS_CLIENT_SECRET: ${CF_ACCESS_CLIENT_SECRET}
      KANBAN_URL: http://kanban:8000
      OBSIDIAN_URL: http://obsidian:8000
      FINANCE_URL: http://finance:8000
      FINANCE_OCR_URL: http://finance-ocr:8000
      ASSET_QUOTES_URL: http://asset-quotes:8000
      PORTFOLIO_URL: http://portfolio:8000
      PORT: 3000
    restart: unless-stopped
    networks:
      - apis

  kanban:
    image: re.giomartins.dev/kanban:latest
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  obsidian:
    image: re.giomartins.dev/obsidian:latest
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  finance:
    image: re.giomartins.dev/finance:latest
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  finance-ocr:
    image: re.giomartins.dev/finance-ocr:latest
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
      FINANCE_URL: http://finance:8000/transactions
    restart: unless-stopped
    networks:
      - apis

  asset-quotes:
    image: re.giomartins.dev/asset-quotes:latest
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  portfolio:
    image: re.giomartins.dev/portfolio:latest
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

networks:
  apis:
    driver: bridge
  persistence:
    external: true
    name: persistence
