"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _home_kpis from './home-kpis.bones.json'
import _home_activity from './home-activity.bones.json'
import _settings_list from './settings-list.bones.json'

configureBoneyard({"color":"#eceef4","darkColor":"#1f2129","animate":"shimmer","shimmerColor":"#f5f6fa","darkShimmerColor":"#2a2c36","speed":"1.6s","stagger":70,"transition":350})

registerBones({
  "home-kpis": _home_kpis,
  "home-activity": _home_activity,
  "settings-list": _settings_list,
})
