services:
  kanban:
    image: re.giomartins.dev/kanban:latest
    container_name: kanban
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  obsidian:
    image: re.giomartins.dev/obsidian:latest
    container_name: obsidian
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  finance:
    image: re.giomartins.dev/finance:latest
    container_name: finance
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  finance-ocr:
    image: re.giomartins.dev/finance-ocr:latest
    container_name: finance-ocr
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
      FINANCE_URL: http://finance:8000/transactions
    restart: unless-stopped
    networks:
      - apis

  asset-quotes:
    image: re.giomartins.dev/asset-quotes:latest
    container_name: asset-quotes
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  portfolio:
    image: re.giomartins.dev/portfolio:latest
    container_name: portfolio
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  alexa:
    image: re.giomartins.dev/alexa:latest
    container_name: alexa
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    volumes:
      - alexa_data:/data/alexa
    networks:
      - apis

networks:
  apis:
    name: apis
    driver: bridge
  persistence:
    external: true

volumes:
  alexa_data:
