services:
  finance:
    image: re.giomartins.dev/finance:latest
    container_name: finance
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  finance-ocr:
    image: re.giomartins.dev/finance-ocr:latest
    container_name: finance-ocr
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
      FINANCE_URL: http://finance:8000/transactions
    restart: unless-stopped
    networks:
      - apis

  asset-quotes:
    image: re.giomartins.dev/asset-quotes:latest
    container_name: asset-quotes
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  portfolio:
    image: re.giomartins.dev/portfolio:latest
    container_name: portfolio
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  whatsapp:
    image: re.giomartins.dev/whatsapp:latest
    container_name: whatsapp
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  domain-data-insights:
    image: re.giomartins.dev/domain-data-insights:latest
    container_name: domain-data-insights
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  settings:
    image: re.giomartins.dev/settings:latest
    container_name: settings
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

  transcription:
    image: re.giomartins.dev/transcription:latest
    container_name: transcription
    environment:
      WHISPER_MODEL: small
      WHISPER_DEVICE: cpu
      WHISPER_COMPUTE_TYPE: int8
    volumes:
      - transcription-model-cache:/model-cache
    restart: unless-stopped
    networks:
      - apis

  bus-tracker:
    image: re.giomartins.dev/bus-tracker:latest
    container_name: bus-tracker
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
    restart: unless-stopped
    networks:
      - apis
      - persistence

networks:
  apis:
    name: apis
    driver: bridge
  persistence:
    external: true

volumes:
  transcription-model-cache:
