services:
  whatsapp-worker:
    image: re.giomartins.dev/whatsapp-worker:latest
    container_name: whatsapp-worker
    restart: unless-stopped
    networks:
      - persistence
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod

  bzzoiro-acl:
    image: re.giomartins.dev/bzzoiro-acl:latest
    container_name: bzzoiro-acl
    restart: unless-stopped
    networks:
      - persistence
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
      OTEL_SERVICE_NAME: bzzoiro-acl
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf

  domain-persister:
    image: re.giomartins.dev/domain-persister:latest
    container_name: domain-persister
    restart: unless-stopped
    networks:
      - persistence
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
      OTEL_SERVICE_NAME: domain-persister
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf

  value-bets-report:
    image: re.giomartins.dev/value_bets_report:latest
    container_name: value-bets-report
    restart: unless-stopped
    networks:
      - persistence
      - apis
    environment:
      if_id: ${IF_ID}
      if_secret: ${IF_SECRET}
      if_project_id: ${IF_PROJECT_ID}
      if_env: prod
      OTEL_SERVICE_NAME: value-bets-report
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf

networks:
  persistence:
    external: true
  apis:
    external: true
